# Generated by Django 3.2.7 on 2021-09-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilender', '0002_auto_20210907_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='sites',
            new_name='site_id',
        ),
    ]
