# Generated by Django 3.2.7 on 2021-09-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilender', '0003_rename_sites_orders_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilender.sites'),
        ),
    ]
